# Generated by Django 5.0.2 on 2024-02-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_img',
            field=models.FileField(upload_to='recipeImages'),
        ),
    ]
